// src/lib/templates/page/Skills.svelte
<script lang="ts">
  import SectionName from '$lib/components/element/SectionName.svelte';
  import SkillList from '$lib/components/modules/SkillList.svelte';
  import skills from '$lib/data/skills';
</script>

<section id="skills">
  <SectionName>My Skills</SectionName>

  <div class="flex flex-wrap justify-center px-10 mx-auto mt-6 max-w-3xl">
    <SkillList {skills} />
  </div>
</section>

// components/Skills.vue
<template>
  <div>
    <h2>Skills</h2>
    <div class="d-flex flex-wrap mx-lg-5" style="justify-content:center;">
      <SkillCard v-for="skill in skills" :key="skill" :skill="skill" />
    </div>
  </div>
</template>

<script>
import SkillCard from '~/components/SkillCard.vue'
import skills from '~/assets/Skills.json'
export default {
  components: { SkillCard },
  data: () => {
    return {
      skills
    }
  }
}
</script>
